apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-manager
  template:
    metadata:
      labels:
        app: task-manager
    spec:
      containers:
        - name: task-manager
          image: vishwajeet/task-manager:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://host.docker.internal:27017/task-manager
